// Pure construction of a duplicated ServerConnection record. Extracted from
// stores/connections.ts so the field-copy rules are unit-testable without
// pulling in zustand/expo (which have no resolver outside Metro).
import type { ServerConnection } from "./types";

/**
 * Build the record for a duplicate of `source`.
 *
 * - `id` must be freshly generated by the caller (it keys SecureStore
 *   password/header storage — reusing the source id would alias secrets).
 * - The copy is never `active`: duplicating a server must not steal the
 *   live SSE/client session from the original.
 * - `lastConnected` is cleared: the copy has never connected.
 * - Everything else (url, directory, username, type, authHeaderKeys) is
 *   carried over — that is the point of duplicating.
 */
export function buildDuplicate(
  source: ServerConnection,
  id: string,
  name: string,
): ServerConnection {
  return {
    ...source,
    id,
    name,
    active: false,
    lastConnected: undefined,
  };
}
